name: UiPath CI/CD Pipeline
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
 
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Download UiPath CLI
        run: |
          Invoke-WebRequest https://uipath.pkgs.visualstudio.com/Public.Feeds/_apis/packaging/feeds/UiPath-Internal/nuget/packages/UiPath.CLI.Windows/versions/23.10.0/content -OutFile uipathcli.zip
        shell: powershell
 
      - name: Extract CLI
        run: Expand-Archive uipathcli.zip -DestinationPath uipathcli
        shell: powershell
 
      - name: Pack UiPath Project
        run: .\uipathcli\uipath.exe pack . --output ./package
 
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uipath-package
          path: package/*.nupkg
