name: UiPath CI Pipeline

on:
 push:
  branches: [ main ]

jobs:
 build:
  runs-on: windows-latest


  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Setup UiPath CLI
    uses: UiPath/setup-uipath-cli@v1

  - name: Pack UiPath Project
    shell: pwsh
    run: |
      uipath pack .

